name: user_repository
description: Dart package to manage user
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  bloc: ^8.1.0
  cloud_firestore: ^4.3.1
  equatable: ^2.0.5
  firebase_auth: ^4.2.5
  geolocator: ^9.0.2
  json_annotation: ^4.8.0

dev_dependencies:
  json_serializable: ^6.6.0
  build_runner: ^2.3.3
