name: map_app_test
description: App that shows current users location on a map

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  geolocation_repository:
    path: packages/geolocation_repository
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flow_builder: ^0.0.9


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  google_sign_in: ^5.4.4
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.3
  geocoding: ^2.0.5
  flutter_google_places: ^0.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

