name: authentication_repository
description: Package to manage user authentication
version: 0.0.1

publish_to: none


environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1

  flutter:
    sdk: flutter
  google_sign_in: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


  