// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1_MToUas_6e-l40sb-fwv5OYBBfF3jsE',
    appId: '1:636588639967:web:47e773d55339d8e948cb6a',
    messagingSenderId: '636588639967',
    projectId: 'map-app-test-86db6',
    authDomain: 'map-app-test-86db6.firebaseapp.com',
    storageBucket: 'map-app-test-86db6.appspot.com',
    measurementId: 'G-7Z22SLYRGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCufk4YERmyl_hlHakqCyvY-08LnzR5ddI',
    appId: '1:636588639967:android:2641b785d125b0b948cb6a',
    messagingSenderId: '636588639967',
    projectId: 'map-app-test-86db6',
    storageBucket: 'map-app-test-86db6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpJaScx0VZHPAXJPWjAJCtovmR1_BsKZM',
    appId: '1:636588639967:ios:30be6aa781eadfa948cb6a',
    messagingSenderId: '636588639967',
    projectId: 'map-app-test-86db6',
    storageBucket: 'map-app-test-86db6.appspot.com',
    androidClientId: '636588639967-ap512l9senfo8c52pi5prjo6rpkh8iqm.apps.googleusercontent.com',
    iosClientId: '636588639967-5eknokge2g4a8e7nc4dml41avjd0c8jq.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapAppTest',
  );
}
